In [1]:
import numpy as np
import pandas as pd

In [2]:
final = pd.read_csv('raw_data/final.csv')

/usr/local/Cellar/ipython@5/5.5.0_4/libexec/lib/python2.7/site-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (56,58) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [3]:
def find_course(year, term, department1, course_number1):
    df = final[(final['year'] == year) & 
               (final['term'] == term) &
               (final['course_number1'] == course_number1) &
               (final['department1'] == department1)]
    return df

In [10]:
final[(final.year==2017) & (final.term=='fall')].shape

(1249, 66)

In [9]:
find_course(2017, 'spring', 'MATH', '101')

,Unnamed: 0,web-scraper-order,web-scraper-start-url,course,comments,year,term,course_title,course_number1,department1,...,Course_Goals_Distribution,Course_Recommend_Distribution,Course_Money_Distribution,Instructor_Return_Distribution,Instructor_Feedback_Distribution,Instructor_Participation_Distribution,Instructor_Enthusiasm_Distribution,Instructor_Accessible_Distribution,Instructor_Lectures_Distribution,Instructor_Overall_Distribution
25425,734,1522924305-38388,https://course-evaluation-reports.fas.harvard....,"MATH 101: Sets, Groups and Topology",[],2017,spring,"Sets, Groups and Topology",101,MATH,...,NaN,"[0, 1, 3, 7, 10]","[20, 1, 0, 0, 0]","[0, 0, 0, 4, 17]","[0, 0, 1, 2, 18]","[0, 0, 0, 2, 19]","[0, 0, 1, 1, 19]","[0, 0, 1, 2, 16]","[0, 0, 0, 3, 15]","[0, 0, 0, 2, 16]"

In [3]:
final

,Unnamed: 0,web-scraper-order,web-scraper-start-url,course,comments,year,term,course_title,course_number1,department1,...,Course_Goals_Distribution,Course_Recommend_Distribution,Course_Money_Distribution,Instructor_Return_Distribution,Instructor_Feedback_Distribution,Instructor_Participation_Distribution,Instructor_Enthusiasm_Distribution,Instructor_Accessible_Distribution,Instructor_Lectures_Distribution,Instructor_Overall_Distribution
0,0,1522891683-18234,https://course-evaluation-reports.fas.harvard....,AFRAMER 112: Black Humor: Performance Art and...,[],2006,fall,Black Humor: Performance Art and Literature,112,AFRAMER,...,NaN,"[3, 1, 0, 2, 15]",NaN,"[0, 1, 2, 2, 15]","[0, 1, 2, 7, 10]","[0, 0, 1, 3, 16]","[0, 0, 3, 1, 16]","[0, 0, 2, 3, 14]","[1, 0, 1, 4, 3]","[0, 0, 1, 3, 3]"
1,1,1522891674-18223,https://course-evaluation-reports.fas.harvard....,"AFRAMER 113: Fictions of Race, Facts of Racis...",[],2006,fall,"Fictions of Race, Facts of Racism: Perspective...",113,AFRAMER,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,1522891670-18217,https://course-evaluation-reports.fas.harvard....,AFRAMER 116: Autobiography and Literary Imagi...,[],2006,fall,Autobiography and Literary Imagination,116,AFRAMER,...,NaN,"[0, 0, 0, 1, 3]",NaN,"[0, 0, 0, 2, 2]","[0, 1, 0, 1, 2]","[0, 0, 1, 2, 1]","[0, 0, 0, 1, 3]","[0, 1, 0, 0, 3]","[0, 1, 0, 0, 2]","[0, 1, 0, 0, 2]"
3,3,1522891657-18200,https://course-evaluation-reports.fas.harvard....,AFRAMER 175: Introduction to African Music,[],2006,fall,Introduction to African Music,175,AFRAMER,...,NaN,"[0, 0, 0, 4, 9]",NaN,"[0, 0, 1, 3, 9]","[0, 0, 2, 3, 7]","[0, 1, 5, 1, 2]","[0, 0, 1, 4, 8]","[0, 1, 0, 3, 6]","[0, 2, 2, 6, 2]","[0, 1, 3, 4, 2]"
4,4,1522891495-18013,https://course-evaluation-reports.fas.harvard....,AFRAMER 190: African-American Families: Polit...,[],2006,fall,"African-American Families: Politics, Culture, ...",190,AFRAMER,...,NaN,"[0, 0, 1, 2, 4]",NaN,"[0, 0, 1, 2, 4]","[0, 0, 1, 4, 2]","[0, 1, 1, 0, 4]","[0, 0, 1, 3, 3]","[0, 0, 1, 1, 5]","[0, 0, 1, 2, 3]","[0, 0, 1, 1, 4]"